project:
  root_dir: "/home/e.mesheryakou/other/dddguard/"
  source_dir: "src/dddguard"
  tests_dir: "tests"
  docs_dir: "docs"
    
scanner:
  # Directories to completely exclude from scanning
  exclude_dirs:
    - ".git"
    - ".venv"
    - "venv"
    - "__pycache__"
    - "node_modules"
    - "migrations"
    - "build"
    - "dist"
    - ".idea"
    - ".vscode"

  # Specific files to ignore during analysis
  ignore_files:
    - "12312312312_example.py"